In [1]:
import pandas as pd
import numpy as np
import joblib
import os

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.feature_selection import RFECV

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [2]:
df = pd.read_csv("../data/processed/customer_churn_cleaned.csv")

In [3]:
X = df.drop(columns=["churn_flag"])
y = df["churn_flag"]

In [4]:
id_columns = [
    "customer_id",
    "legacy_customer_code",
    "crm_reference_number",
    "marketing_batch_id"
]

X = X.drop(
    columns=id_columns,
    errors="ignore"
)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [6]:
numeric_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()


numeric_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)


categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)


preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

In [7]:
feature_selector = RFECV(
    estimator=LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    step=1,
    cv=5,
    scoring="f1",
    min_features_to_select=5,
    n_jobs=-1
)

In [8]:
def create_pipeline(classifier):

    return ImbPipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "feature_selection",
                feature_selector
            ),
            (
                "smote",
                SMOTE(random_state=42)
            ),
            (
                "classifier",
                classifier
            )
        ]
    )

In [9]:
X_train_processed = preprocessor.fit_transform(
    X_train
)

X_test_processed = preprocessor.transform(
    X_test
)

feature_names = preprocessor.get_feature_names_out()

rfecv = RFECV(
    estimator=LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    step=1,
    cv=5,
    scoring="f1",
    min_features_to_select=5,
    n_jobs=-1
)

rfecv.fit(
    X_train_processed,
    y_train
)

selected_mask = rfecv.support_

print(
    "Selected features:",
    selected_mask.sum()
)

Selected features: 15

In [10]:
X_train_selected = X_train_processed[
    :, selected_mask
]

X_test_selected = X_test_processed[
    :, selected_mask
]

print(
    "Training shape after feature selection:",
    X_train_selected.shape
)

print(
    "Testing shape after feature selection:",
    X_test_selected.shape
)

Training shape after feature selection: (40000, 15)
Testing shape after feature selection: (10000, 15)

In [11]:
smote = SMOTE(
    random_state=42
)

X_train_balanced, y_train_balanced = smote.fit_resample(
    X_train_selected,
    y_train
)

print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(y_train_balanced.value_counts())

Before SMOTE:
churn_flag
0    29234
1    10766
Name: count, dtype: int64

After SMOTE:
churn_flag
0    29234
1    29234
Name: count, dtype: int64

In [12]:
logistic_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

logistic_model.fit(
    X_train_balanced,
    y_train_balanced
)

LogisticRegression(max_iter=2000, random_state=42)

In [13]:
random_forest_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

random_forest_model.fit(
    X_train_balanced,
    y_train_balanced
)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [14]:
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(
    X_train_balanced,
    y_train_balanced
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [15]:
models = {
    "Logistic Regression": logistic_model,
    "Random Forest": random_forest_model,
    "XGBoost": xgb_model
}

results = []

for name, model in models.items():

    y_pred = model.predict(
        X_test_selected
    )

    y_probability = model.predict_proba(
        X_test_selected
    )[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(
            y_test,
            y_pred
        ),
        "Precision": precision_score(
            y_test,
            y_pred
        ),
        "Recall": recall_score(
            y_test,
            y_pred
        ),
        "F1": f1_score(
            y_test,
            y_pred
        ),
        "ROC-AUC": roc_auc_score(
            y_test,
            y_probability
        )
    })

results_df = pd.DataFrame(results)

results_df.sort_values(
    "F1",
    ascending=False
)

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
2              XGBoost    0.8025   0.602814  0.780007  0.680058  0.865570
1        Random Forest    0.7866   0.593866  0.654775  0.622835  0.843623
0  Logistic Regression    0.7461   0.519457  0.753995  0.615128  0.818315

In [16]:
best_model_name = results_df.sort_values(
    "F1",
    ascending=False
).iloc[0]["Model"]

best_model = models[best_model_name]

print("Best model:", best_model_name)

Best model: XGBoost

In [17]:
os.makedirs("../models", exist_ok=True)

joblib.dump(
    best_model,
    "../models/best_churn_model.pkl"
)

joblib.dump(
    preprocessor,
    "../models/preprocessor.pkl"
)

joblib.dump(
    rfecv,
    "../models/feature_selector.pkl"
)

joblib.dump(
    selected_mask,
    "../models/selected_feature_mask.pkl"
)

print("Models saved successfully.")

Models saved successfully.

In [18]:
selected_feature_names = feature_names[
    selected_mask
]

pd.DataFrame({
    "selected_feature": selected_feature_names
}).to_csv(
    "../reports/final_selected_features.csv",
    index=False
)

print("Final selected features:")
for feature in selected_feature_names:
    print("✓", feature)

Final selected features:
✓ num__customer_tenure_months
✓ num__network_drop_rate
✓ num__service_outages_last_6m
✓ num__late_payments_last_12m
✓ cat__gender_Female
✓ cat__gender_Male
✓ cat__customer_segment_Business
✓ cat__customer_segment_Consumer
✓ cat__customer_segment_Family
✓ cat__customer_segment_Premium
✓ cat__plan_type_Prepaid
✓ cat__plan_type_Unlimited
✓ cat__contract_type_1 Year
✓ cat__contract_type_2 Year
✓ cat__contract_type_Month-to-Month

In [19]:
# ============================================================
# LOAD PREPROCESSOR AND FEATURE SELECTION
# ============================================================

preprocessor = joblib.load(
    "../models/preprocessor.pkl"
)

feature_selection_results = joblib.load(
    "../models/feature_selection_results.pkl"
)

X_train_processed = preprocessor.transform(
    X_train
)

X_test_processed = preprocessor.transform(
    X_test
)

print(
    "Processed training shape:",
    X_train_processed.shape
)

Processed training shape: (40000, 46)

In [20]:
# ============================================================
# FEATURE INDICES
# ============================================================

feature_names = (
    preprocessor
    .get_feature_names_out()
)

feature_to_index = {
    feature: index
    for index, feature
    in enumerate(feature_names)
}

experiment_indices = {}

for experiment, features in feature_selection_results.items():

    experiment_indices[experiment] = [
        feature_to_index[feature]
        for feature in features
    ]

    print(
        experiment,
        "→",
        len(experiment_indices[experiment]),
        "features"
    )

experiment_1 → 15 features
experiment_2 → 15 features
experiment_3 → 15 features

In [21]:
# ============================================================
# XGBOOST TRAINING FUNCTION
# ============================================================

def train_xgb(
    X_train,
    y_train
):

    model = XGBClassifier(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=6,
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train
    )

    return model

In [22]:
# ============================================================
# EVALUATION FUNCTION
# ============================================================

def evaluate_model(
    model,
    X_test,
    y_test
):

    y_pred = model.predict(
        X_test
    )

    y_probability = (
        model.predict_proba(X_test)[:, 1]
    )

    return {
        "Precision": precision_score(
            y_test,
            y_pred
        ),

        "Recall": recall_score(
            y_test,
            y_pred
        ),

        "F1 Score": f1_score(
            y_test,
            y_pred
        ),

        "ROC AUC": roc_auc_score(
            y_test,
            y_probability
        )
    }

In [23]:
# ============================================================
# TRAIN ALL THREE FEATURE-SELECTION EXPERIMENTS
# ============================================================

from imblearn.over_sampling import SMOTE

experiment_results = []
trained_models = {}

for experiment_name, indices in experiment_indices.items():

    print("\n" + "=" * 60)
    print(experiment_name)
    print("=" * 60)

    # --------------------------------------------------------
    # SELECT FEATURES
    # --------------------------------------------------------

    X_train_selected = X_train_processed[:, indices]

    X_test_selected = X_test_processed[:, indices]

    print(
        "Selected features:",
        X_train_selected.shape[1]
    )

    # --------------------------------------------------------
    # SMOTE - TRAINING DATA ONLY
    # --------------------------------------------------------

    smote = SMOTE(
        random_state=42
    )

    X_train_balanced, y_train_balanced = (
        smote.fit_resample(
            X_train_selected,
            y_train
        )
    )

    print(
        "Before SMOTE:",
        X_train_selected.shape
    )

    print(
        "After SMOTE:",
        X_train_balanced.shape
    )

    # --------------------------------------------------------
    # TRAIN XGBOOST
    # --------------------------------------------------------

    model = train_xgb(
        X_train_balanced,
        y_train_balanced
    )

    # --------------------------------------------------------
    # PREDICT ON ORIGINAL TEST DATA
    # --------------------------------------------------------

    y_pred = model.predict(
        X_test_selected
    )

    y_probability = model.predict_proba(
        X_test_selected
    )[:, 1]

    # --------------------------------------------------------
    # CALCULATE METRICS
    # --------------------------------------------------------

    precision = precision_score(
        y_test,
        y_pred
    )

    recall = recall_score(
        y_test,
        y_pred
    )

    f1 = f1_score(
        y_test,
        y_pred
    )

    roc_auc = roc_auc_score(
        y_test,
        y_probability
    )

    # --------------------------------------------------------
    # STORE RESULTS
    # --------------------------------------------------------

    experiment_results.append({
        "Experiment": experiment_name,
        "Features": len(indices),
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC AUC": roc_auc
    })

    trained_models[
        experiment_name
    ] = model

    print(
        f"Precision: {precision:.4f}"
    )

    print(
        f"Recall:    {recall:.4f}"
    )

    print(
        f"F1 Score:  {f1:.4f}"
    )

    print(
        f"ROC AUC:   {roc_auc:.4f}"
    )

============================================================
experiment_1
============================================================
Selected features: 15
Before SMOTE: (40000, 15)
After SMOTE: (58468, 15)
Precision: 0.6055
Recall:    0.7808
F1 Score:  0.6820
ROC AUC:   0.8675

============================================================
experiment_2
============================================================
Selected features: 15
Before SMOTE: (40000, 15)
After SMOTE: (58468, 15)
Precision: 0.6119
Recall:    0.7674
F1 Score:  0.6808
ROC AUC:   0.8659

============================================================
experiment_3
============================================================
Selected features: 15
Before SMOTE: (40000, 15)
After SMOTE: (58468, 15)
Precision: 0.6087
Recall:    0.7562
F1 Score:  0.6745
ROC AUC:   0.8688

In [24]:
# ============================================================
# EXPERIMENT COMPARISON
# ============================================================

comparison = pd.DataFrame(
    experiment_results
)

comparison = comparison[
    [
        "Experiment",
        "Features",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC AUC"
    ]
].sort_values(
    by="F1 Score",
    ascending=False
).reset_index(
    drop=True
)

comparison

     Experiment  Features  Precision    Recall  F1 Score   ROC AUC
0  experiment_1        15   0.605476  0.780751  0.682032  0.867527
1  experiment_2        15   0.611852  0.767373  0.680844  0.865863
2  experiment_3        15   0.608735  0.756224  0.674511  0.868791

In [26]:
# ============================================================
# SELECT BEST EXPERIMENT
# ============================================================

best_experiment = (
    comparison
    .iloc[0]["Experiment"]
)

best_f1 = (
    comparison
    .iloc[0]["F1 Score"]
)

best_model = (
    trained_models[
        best_experiment
    ]
)

best_indices = (
    experiment_indices[
        best_experiment
    ]
)

print("🏆 BEST EXPERIMENT")
print(
    best_experiment
)

print(
    f"F1 Score: {best_f1:.4f}"
)

print(
    f"Features: {len(best_indices)}"
)

🏆 BEST EXPERIMENT
experiment_1
F1 Score: 0.6820
Features: 15

In [27]:
# ============================================================
# SAVE EXPERIMENT COMPARISON
# ============================================================

comparison.to_csv(
    "../models/model_comparison.csv",
    index=False
)

print(
    "Model comparison saved."
)

Model comparison saved.

In [28]:
# ============================================================
# SAVE WINNING MODEL
# ============================================================

joblib.dump(
    best_model,
    "../models/best_churn_model.pkl"
)

joblib.dump(
    best_indices,
    "../models/best_feature_indices.pkl"
)

joblib.dump(
    best_experiment,
    "../models/best_experiment.pkl"
)

print(
    "Winning model and feature indices saved."
)

Winning model and feature indices saved.

In [29]:
# ============================================================
# FINAL CONFUSION MATRIX
# ============================================================

X_test_best = (
    X_test_processed[:, best_indices]
)

final_predictions = (
    best_model.predict(X_test_best)
)

cm = confusion_matrix(
    y_test,
    final_predictions,
    labels=[0, 1]
)

print(cm)

[[5940 1369]
 [ 590 2101]]

In [30]:
# ============================================================
# FINAL CLASSIFICATION REPORT
# ============================================================

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        final_predictions
    )
)

              precision    recall  f1-score   support

           0       0.91      0.81      0.86      7309
           1       0.61      0.78      0.68      2691

    accuracy                           0.80     10000
   macro avg       0.76      0.80      0.77     10000
weighted avg       0.83      0.80      0.81     10000

In [31]:
import joblib

saved_model = joblib.load(
    "../models/best_churn_model.pkl"
)

saved_indices = joblib.load(
    "../models/best_feature_indices.pkl"
)

saved_preprocessor = joblib.load(
    "../models/preprocessor.pkl"
)

print("Saved model features:", saved_model.n_features_in_)
print("Saved indices:", len(saved_indices))
print(
    "Saved preprocessor features:",
    len(saved_preprocessor.get_feature_names_out())
)

Saved model features: 15
Saved indices: 15
Saved preprocessor features: 46

In [32]:
X_test_processed_saved = saved_preprocessor.transform(X_test)

X_test_selected_saved = X_test_processed_saved[
    :,
    saved_indices
]

saved_pred = saved_model.predict(
    X_test_selected_saved
)

saved_probability = saved_model.predict_proba(
    X_test_selected_saved
)[:, 1]

print(
    "Saved model F1:",
    f1_score(y_test, saved_pred)
)

print(
    "Saved model Recall:",
    recall_score(y_test, saved_pred)
)

print(
    "Saved model Precision:",
    precision_score(y_test, saved_pred)
)

print(
    "Saved model ROC-AUC:",
    roc_auc_score(y_test, saved_probability)
)

Saved model F1: 0.6820321376399935
Saved model Recall: 0.7807506503158677
Saved model Precision: 0.6054755043227665
Saved model ROC-AUC: 0.8675267568442748